### ISSUE TITLE
Tegral is not compatible with Ktor 3.0.0

### ISSUE THREAD

**Issue by AlejandroYuste** [utybo/Tegral#100]
Tegral is not longer compatible with latest Ktor versions.

`Exception in thread "main" java.lang.NoClassDefFoundError: io/ktor/server/routing/RoutingKt
	at guru.zoroark.tegral.openapi.ktor.DescribeSubroutesKt.describeSubroutes(DescribeSubroutes.kt:28)`

**Comment by utybo** [comment]
This is fixed by #103 (which also includes several other updates).

Unfortunately, snapshots publishing is broken right now, so you can't download it just yet, sorry about that 😅

**Comment by utybo** [comment]
Snapshots are alive again, you can use version `0.0.5-SNAPSHOT` for now

**Comment by AlejandroYuste** [comment]
Any idea when it will be available as a release?

**Comment by JulianAtSAP** [comment]
@AlejandroYuste did you find out?

**Comment by utybo** [comment]
Hey folks, apologies for the silence here - Tegral is made entirely in my free time, which I have not had a lot of these past few months unfortunately.

I'll try to push a release within the next few weeks. In the mean time, you can use the regular Maven Central snapshots repository (repository URL is `https://s01.oss.sonatype.org/content/repositories/snapshots`). All commits on `main` are automatically published there.

I'm pretty sure Tegral can also be used via Jitpack.io but I haven't tested that in a while.

**Comment by AlejandroYuste** [comment]
Hey, no worries or rush. All good
