### ISSUE TITLE
OpenAPI DSL does not support root security declarations

### ISSUE THREAD

**Issue by anthony-legay** [utybo/Tegral#106]
It seems the OpenAPI DSL does not support declarations of `security` at root level like the specification offers it.
(see [documentation here](https://swagger.io/docs/specification/v3_0/authentication/) )

I made a PR by adding a `SecurityDsl` to merge declarations on root level and operation level: https://github.com/utybo/Tegral/pull/101

What do you think about this ?

**Comment by utybo** [comment]
Thanks a lot for your contribution 🙏🏻 Apologies for the lack of response from my end, I'm pretty busy these days 😅 

I'll have a look at your PR right away
