### ISSUE TITLE
Published artifacts require Java 17

### ISSUE THREAD

**Issue by serras** [utybo/Tegral#44]
The artifacts published in Maven somehow make my projects require Java 17 to run. Although this is an LTS, it would be great if artifacts required only Java 11, broadening the user base.

Pinging my colleague @nomisRev who's also interested in requiring a lesser version of the JDK.

**Comment by utybo** [comment]
Yup, that's a mistake on my end. JDK 11 should be the minimum version (can't go to JDK 8 because one of the dependencies (I believe Hoplite?) produces JDK 11 bytecode that can't be properly inlined).

I believe that's just a Gradle setting somewhere, I'll have a look

**Comment by nomisRev** [comment]
@utybo I think it's because the published artefacts are build with JDK 17.

https://github.com/utybo/Tegral/blob/d7f9f38b40ed3a0f7b2cda3ef0db40a4c9074073/.github/workflows/ci.yaml#L189

Changing the version here to `11` should fix the problem IIRC.

**Comment by utybo** [comment]
Reopening this, I'd like to check if the published snapshot works properly with Java 11 before closing

**Comment by nomisRev** [comment]
@utybo is there a snapshot available we could test for you?

**Comment by utybo** [comment]
> @utybo is there a snapshot available we could test for you? 

@nomisRev You should be able to try 0.0.3-SNAPSHOT which is built from main. Lmk if everything works for you with that version :)

**Comment by nomisRev** [comment]
Hey @utybo,

I cannot share the repo I tested this on since it's currently still _private_. I tested by simply updating to `0.3.0-SNAPSHOT`, including the `SNAPSHOT` repo, and downgrading `Java 17` to `Java 11` both in Gradle and on CI.

**Comment by utybo** [comment]
> Hey @utybo,
> 
> I cannot share the repo I tested this on since it's currently still _private_. I tested by simply updating to `0.3.0-SNAPSHOT`, including the `SNAPSHOT` repo, and downgrading `Java 17` to `Java 11` both in Gradle and on CI.

@nomisRev I'm not sure I understand your reply, did it work properly under Java 11?

**Comment by nomisRev** [comment]
Yes, it works properly under Java 11 👍 I tested it on a private repository.

**Comment by utybo** [comment]
Alright, closing this as done then 👍🏻
