### ISSUE TITLE
Add documentation for headers in response

### ISSUE THREAD

**Issue by thebino** [utybo/Tegral#57]
Having a HttpHeader in the response should be possible to add to the documentation.
For example a `HttpHeaders.Location` which is often the case for `HttpStatusCode.Created`

```kotlin
routing {
    post("/posts") {
        // create new post -> return ID in location header
        val postID = 1
        call.response.headers.append(HttpHeaders.Location, "/post/$postID")
        call.respond(HttpStatusCode.Created)
    } describe {
        summary = "Create a new post"
        201 response {
            description = "A new post has been created."
            "Location" headerParameter {
                // see ParameterDsl
            }
        }
    }
}
```

**Comment by utybo** [comment]
Funnily enough, I've left a `TODO` for it, that will need to be done:

https://github.com/utybo/Tegral/blob/1a47c9f91e51d1e66f84a20e7d8a2c21ded1f3e1/tegral-openapi/tegral-openapi-dsl/src/main/kotlin/guru/zoroark/tegral/openapi/dsl/ResponseDsl.kt#LL31C20-L31C20
